"""empty message

Revision ID: 151232379d0d
Revises: 3d4404d8aaf1
Create Date: 2015-03-11 17:18:15.813794

"""

# revision identifiers, used by Alembic.
revision = '151232379d0d'
down_revision = '3d4404d8aaf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data', 'report', ['report_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'report_id')
    ### end Alembic commands ###
