"""empty message

Revision ID: 2d8c58b5e963
Revises: None
Create Date: 2015-03-30 12:03:09.018834

"""

# revision identifiers, used by Alembic.
revision = '2d8c58b5e963'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('reference_month', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created_date'), 'report', ['created_date'], unique=False)
    op.create_table('csvfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('reference_month', sa.Integer(), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=30), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csvfile_created_date'), 'csvfile', ['created_date'], unique=False)
    op.create_table('reportdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.String(length=255), nullable=True),
    sa.Column('total_users', sa.BigInteger(), nullable=True),
    sa.Column('free_users', sa.BigInteger(), nullable=True),
    sa.Column('paid_users', sa.BigInteger(), nullable=True),
    sa.Column('free_users_no_comsumption', sa.BigInteger(), nullable=True),
    sa.Column('free_users_with_comsumption', sa.BigInteger(), nullable=True),
    sa.Column('storage_used', sa.BigInteger(), nullable=True),
    sa.Column('range_between_1', sa.BigInteger(), nullable=True),
    sa.Column('range_between_2', sa.BigInteger(), nullable=True),
    sa.Column('range_between_3', sa.BigInteger(), nullable=True),
    sa.Column('range_between_4', sa.BigInteger(), nullable=True),
    sa.Column('range_between_5', sa.BigInteger(), nullable=True),
    sa.Column('range_between_6', sa.BigInteger(), nullable=True),
    sa.Column('inactives_on_period', sa.BigInteger(), nullable=True),
    sa.Column('acquisition_on_period', sa.BigInteger(), nullable=True),
    sa.Column('regular_users', sa.BigInteger(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notfound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.String(length=40), nullable=True),
    sa.Column('extref', sa.String(length=40), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('quota', sa.BigInteger(), nullable=True),
    sa.Column('usage_quota', sa.BigInteger(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notfound')
    op.drop_table('reportdata')
    op.drop_index(op.f('ix_csvfile_created_date'), table_name='csvfile')
    op.drop_table('csvfile')
    op.drop_index(op.f('ix_report_created_date'), table_name='report')
    op.drop_table('report')
    ### end Alembic commands ###
