"""empty message

Revision ID: 36e3744114e3
Revises: 2d8c58b5e963
Create Date: 2015-04-01 13:52:05.742918

"""

# revision identifiers, used by Alembic.
revision = '36e3744114e3'
down_revision = '2d8c58b5e963'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notfound', sa.Column('quota_usage', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notfound', 'quota_usage')
    ### end Alembic commands ###
