"""empty message

Revision ID: 3d4404d8aaf1
Revises: None
Create Date: 2015-03-11 16:05:31.713491

"""

# revision identifiers, used by Alembic.
revision = '3d4404d8aaf1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created_date'), 'report', ['created_date'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_extref', sa.String(length=255), nullable=True),
    sa.Column('first_use', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('state', sa.BigInteger(), nullable=True),
    sa.Column('total_quota_usage', sa.BigInteger(), nullable=True),
    sa.Column('total_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('object_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('video_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('audio_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('image_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('document_storage_usage', sa.BigInteger(), nullable=True),
    sa.Column('quota', sa.BigInteger(), nullable=True),
    sa.Column('malware_count', sa.BigInteger(), nullable=True),
    sa.Column('total_file_count', sa.BigInteger(), nullable=True),
    sa.Column('object_file_count', sa.BigInteger(), nullable=True),
    sa.Column('video_file_count', sa.BigInteger(), nullable=True),
    sa.Column('audio_file_count', sa.BigInteger(), nullable=True),
    sa.Column('image_file_count', sa.BigInteger(), nullable=True),
    sa.Column('document_file_count', sa.BigInteger(), nullable=True),
    sa.Column('trash_file_count', sa.BigInteger(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_share_count', sa.BigInteger(), nullable=True),
    sa.Column('partner', sa.String(length=255), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_created_date'), 'data', ['created_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_created_date'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_report_created_date'), table_name='report')
    op.drop_table('report')
    ### end Alembic commands ###
