"""empty message

Revision ID: 4d6e1ba99ee2
Revises: 5205c78e66eb
Create Date: 2015-03-12 18:27:01.383298

"""

# revision identifiers, used by Alembic.
revision = '4d6e1ba99ee2'
down_revision = '5205c78e66eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('state', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'state')
    ### end Alembic commands ###
